// Every quantitative or result statement on the site lives here, with the exact
// sentence it comes from. Pages reference claims by id through <Claim> and
// <ResultsTable>; nothing numeric is typed directly into page copy.

export type ClaimKind =
  | 'measured'
  | 'theoretical-bound'
  | 'algebraic-limit'
  | 'analytical'
  | 'simulated'
  | 'model'
  | 'projection';

export const kindLabel: Record<ClaimKind, string> = {
  measured: 'measured',
  'theoretical-bound': 'theoretical bound',
  'algebraic-limit': 'algebraic limit',
  analytical: 'analytical',
  simulated: 'simulated',
  model: 'model',
  projection: 'projection',
};

export interface Claim {
  id: string;
  quantity: string;
  value: string;
  kind: ClaimKind;
  context?: string;
  source: string;
  quote: string;
  status: 'verified' | 'needs-confirmation';
  /** Internal note on conflicts or decisions; never rendered. */
  note?: string;
}

const PR = 'Shukla et al., arXiv:2509.26271v1';
const FQ = 'Kolangatt et al., Phys. Rev. A 110, 032615 (2024)';
const MHV = 'Verma & Chandrashekar, arXiv:2607.02456v1';
const BS = 'Verma, BS thesis, IISc (2024)';
const MS = 'Verma, MS thesis, IISc (2025)';

const list: Claim[] = [
  // CHSH reference values (theory)
  {
    id: 'chsh.local',
    quantity: 'Local (classical) bound on S',
    value: '2',
    kind: 'theoretical-bound',
    source: `${PR}, Fig. 3(c) legend`,
    quote: 'Classical bound (S = 2)',
    status: 'verified',
  },
  {
    id: 'chsh.tsirelson',
    quantity: 'Tsirelson (quantum) bound on S',
    value: '2√2 ≈ 2.83',
    kind: 'theoretical-bound',
    source: `${PR}, Fig. 3(c) legend`,
    quote: 'Tsirelson bound (S = 2√2)',
    status: 'verified',
  },
  {
    id: 'chsh.algebraic',
    quantity: 'Algebraic maximum of S (PR box)',
    value: '4',
    kind: 'algebraic-limit',
    source: `${PR}, Fig. 3(c) legend`,
    quote: 'Algebraic maximum (S = 4)',
    status: 'verified',
  },

  // PR-box simulation
  {
    id: 'pr.chsh',
    quantity: 'CHSH value S in the PR-correlation simulation',
    value: '3.91 ± 0.002',
    kind: 'measured',
    context: 'Four-qubit photonic circuit acting as a non-signalling oracle. Ideal value 4.',
    source: `${PR}, p. 5, after Eq. (7)`,
    quote: 'Under ideal conditions the expected value is S = 4; in our setup we obtain S = 3.91 ± 0.002, close to the maximum achievable value.',
    status: 'verified',
  },
  {
    id: 'pr.fidelity',
    quantity: 'Fidelity of the two-qubit maximally entangled state',
    value: '93.9%',
    kind: 'measured',
    context: 'State generated by the photonic circuit',
    source: `${PR}, pp. 1–2`,
    quote: 'We realize a photonic circuit that generates a two-qubit maximally entangled state with fidelity 93.9%',
    status: 'verified',
  },
  {
    id: 'pr.visibility',
    quantity: 'Visibility',
    value: '> 99%',
    kind: 'measured',
    context: 'Across multiple measurement bases',
    source: `${PR}, p. 2`,
    quote: '…and with visibilities above 99% across multiple bases.',
    status: 'verified',
  },
  {
    id: 'pr.diagonal',
    quantity: 'S in the diagonal basis {|A⟩, |D⟩}',
    value: 'at most 2',
    kind: 'measured',
    context: 'Computational and circular bases approach 4',
    source: `${PR}, Fig. 3(a) caption`,
    quote: 'Computational basis measurement {|H⟩, |V⟩} and circular basis measurement {|L⟩, |R⟩} approach the algebraic maximum S = 4 (PR correlations), whereas diagonal basis {|A⟩, |D⟩} attains at most S = 2.',
    status: 'verified',
  },
  {
    id: 'pr.unentangled',
    quantity: 'PR correlations from an unentangled, classically correlated state',
    value: 'reproduced',
    kind: 'simulated',
    context: 'Numerical simulation, Fig. 3(c)',
    source: `${PR}, p. 2`,
    quote: 'numerical simulations confirm that PR correlations can be obtained without entanglement, but through the preparation of classically correlated states',
    status: 'verified',
  },

  // Four-qubit QRNG (PRA)
  {
    id: 'fq.verified-rate',
    quantity: 'Publicly verified and secured random bits',
    value: '185 kbps',
    kind: 'measured',
    context: 'From collective data of 370 kbps',
    source: `${FQ}, abstract`,
    quote: 'we generate publicly verified and purely secured random bits at the rate of 185 kbps from collective data of 370 kbps.',
    status: 'verified',
    note: 'Conclusion of the same paper states 165 kbps. Abstract value used, as decided with the author on 2026-10-03.',
  },
  {
    id: 'fq.collective-rate',
    quantity: 'Collective bit rate',
    value: '370 kbps',
    kind: 'measured',
    context: 'At 6 mW pump power',
    source: `${FQ}, Sec. III A`,
    quote: 'At a pump power of 6 mW, we reached a bit rate of 370 kbps',
    status: 'verified',
  },
  {
    id: 'fq.verification',
    quantity: 'Sampled bits passing entanglement verification, Eq. (5)',
    value: '97.9%',
    kind: 'measured',
    context: '10% of recorded strings (3 330 856 bits) used as the sample',
    source: `${FQ}, Sec. III C`,
    quote: 'We used 10% of the recorded strings, consisting of 3 330 856 bits, to verify if the outputs satisfy the condition in Eq. (5). Of the sample data, 97.9% met the condition.',
    status: 'verified',
  },
  {
    id: 'fq.nist',
    quantity: 'NIST SP 800-22 tests passed',
    value: '15 of 15',
    kind: 'measured',
    context: 'All four strings, no post-processing',
    source: `${FQ}, Sec. III A`,
    quote: 'All the strings XA, XB, XC, and XD of the generated random numbers passed all 15 NIST tests without any need for postprocessing.',
    status: 'verified',
  },
  {
    id: 'fq.source-fidelity',
    quantity: 'Fidelity of the entangled photon source state',
    value: '98.12%',
    kind: 'measured',
    context: 'Reconstructed density matrix',
    source: `${FQ}, Fig. 3 caption`,
    quote: 'Shows the real and imaginary parts of the reconstructed density matrix of the entangled photons with fidelity 98.12%',
    status: 'verified',
  },
  {
    id: 'fq.visibility',
    quantity: 'Source visibility, H/V and A/D bases',
    value: '98.6% and 98.1%',
    kind: 'measured',
    context: 'Taken at 0.15 mW pump power',
    source: `${FQ}, Fig. 3 caption and Sec. III`,
    quote: 'visibility plot in H/V (98.6%) and A/D (98.1%) basis. … Data were taken at a lower pump power of 0.15 mW so that the accidental counts were minimal',
    status: 'verified',
  },
  {
    id: 'fq.chsh',
    quantity: 'CHSH value of the source photon pairs',
    value: '2.77',
    kind: 'measured',
    source: `${FQ}, Sec. IV`,
    quote: "The entangled source photon pairs used for the generation of four-qubit state and randomness generation gives a Bell's CHSH value of 2.77",
    status: 'verified',
  },
  {
    id: 'fq.noise-model',
    quantity: 'Noise model vs. measured bit rates',
    value: 'agreement reported',
    kind: 'model',
    context: 'Entanglement variation and depolarizing noise, Figs. 6–7',
    source: `${FQ}, abstract`,
    quote: 'The theoretical model of noise on the four-qubit state and its effect on the generation rate of verified and secured bits are in perfect agreement with the experimental results.',
    status: 'verified',
  },

  // Entangled-photon source (BS thesis)
  {
    id: 'bs.chsh',
    quantity: 'CHSH value S',
    value: '2.729',
    kind: 'measured',
    context: 'Computed from the coincidence counts in Table 5.1',
    source: `${BS}, Table 5.1, p. 41`,
    quote: 'S 2.729230425',
    status: 'verified',
    note: 'Text says 0.1 mW, table header says 6 mW. Pump power deliberately not shown.',
  },
  {
    id: 'bs.fidelity',
    quantity: 'State fidelity from tomography',
    value: '93.9%',
    kind: 'measured',
    source: `${BS}, Sec. 5.3, p. 44`,
    quote: 'FIDELITY 93.9',
    status: 'verified',
  },
  {
    id: 'bs.rate',
    quantity: 'Random bit rate',
    value: '138 kbps',
    kind: 'measured',
    context: 'At 6 mW pump power',
    source: `${BS}, abstract`,
    quote: 'With a 6mW pump power, we achieve a 138kbps bitrate',
    status: 'verified',
  },
  {
    id: 'bs.nist',
    quantity: 'NIST randomness tests passed',
    value: '15',
    kind: 'measured',
    context: 'Without post-processing',
    source: `${BS}, abstract`,
    quote: 'These quantum random numbers generated using this method pass 15 NIST tests for randomness without post-processing.',
    status: 'verified',
  },
  {
    id: 'bs.scaling',
    quantity: 'Bit rate scaling',
    value: '10 Mbps',
    kind: 'projection',
    source: `${BS}, abstract`,
    quote: 'scalable to 10Mbps without multiphoton effects',
    status: 'verified',
  },

  // MHV quantum walks
  {
    id: 'mhv.numerics',
    quantity: 'Low-point gluon amplitudes from the quantum walk',
    value: 'consistent with analytical results',
    kind: 'simulated',
    context: 'Comparison in Table II',
    source: `${MHV}, abstract`,
    quote: 'numerical results for low-point gluon amplitudes demonstrate that the proposed representation faithfully captures the characteristic Parke–Taylor structure and is consistent with analytical results.',
    status: 'verified',
  },
  {
    id: 'mhv.sectors',
    quantity: 'Terminal permutation sectors',
    value: '(n − 1)!',
    kind: 'analytical',
    source: `${MHV}, Appendix F, Eq. (F1)`,
    quote: 'N_term = (n − 1)!',
    status: 'verified',
  },
  {
    id: 'mhv.growth',
    quantity: 'Tree nodes g(n) and walk dimension D(n) for n = 4, 5, 6',
    value: '16 / 48, 65 / 260, 326 / 1630',
    kind: 'analytical',
    source: `${MHV}, Table VI`,
    quote: 'n g(n) D(n): 4 16 48; 5 65 260; 6 326 1630',
    status: 'verified',
  },

  // Monitored fermions (MS thesis)
  {
    id: 'ms.crossover',
    quantity: 'Entanglement vs. measurement strength',
    value: 'log-law to area-law crossover',
    kind: 'simulated',
    context: 'Finite but large systems; benchmarked against earlier work',
    source: `${MS}, abstract`,
    quote: 'The system exhibits a sharp crossover from long-time steady with entanglement entropy varying logarithmically with subsystem size to a steady state with area-law entanglement as function of measurement strength for finite but large system sizes.',
    status: 'verified',
  },
  {
    id: 'ms.oscillations',
    quantity: 'Local observables, weak vs. strong monitoring',
    value: 'oscillations for γ < 1, Zeno suppression for γ > 1',
    kind: 'simulated',
    source: `${MS}, Ch. 3`,
    quote: 'weak monitoring (γ < 1) preserves coherent oscillations in local observables, while strong measurements (γ > 1) lead to suppression of quantum fluctuations through the quantum Zeno effect.',
    status: 'verified',
  },
  {
    id: 'ms.diffusive',
    quantity: 'Connected density–density correlation',
    value: 'diffusive decay',
    kind: 'simulated',
    context: 'Both typical and normal averaging',
    source: `${MS}, Ch. 3`,
    quote: 'The connected density-density correlation function shows diffusive decay, for both typical and normal averaging.',
    status: 'verified',
  },
  {
    id: 'ms.current',
    quantity: 'Current–current correlations',
    value: 'decay faster as γ increases',
    kind: 'simulated',
    source: `${MS}, Ch. 3`,
    quote: 'Current-current correlations decay faster with increasing γ, demonstrating how measurements hinder coherent transport in the system.',
    status: 'verified',
  },
  {
    id: 'ms.response',
    quantity: 'Density–density response function',
    value: 'vanishes',
    kind: 'simulated',
    context: 'Suggests an infinite-temperature-like state',
    source: `${MS}, Ch. 3`,
    quote: 'The vanishing density-density response function suggests that strong monitoring drives the system toward an infinite-temperature-like state.',
    status: 'verified',
  },
];

const byId = new Map<string, Claim>();
for (const c of list) {
  if (byId.has(c.id)) throw new Error(`Duplicate claim id: ${c.id}`);
  if (!c.source || !c.quote) throw new Error(`Claim ${c.id} is missing its source or quote`);
  byId.set(c.id, c);
}

export const claims = list;

/** Look up a claim. In production builds, unknown or unconfirmed claims fail the build. */
export function getClaim(id: string): Claim {
  const c = byId.get(id);
  if (!c) throw new Error(`Unknown claim id "${id}"`);
  if (c.status !== 'verified' && import.meta.env?.PROD) {
    throw new Error(`Claim "${id}" is not confirmed and cannot be published`);
  }
  if (c.kind === 'projection') {
    throw new Error(`Claim "${id}" is a projection; projections are not shown on the site`);
  }
  return c;
}
